env: "dev"

DB_INFO:
  host: "localhost"
  name: "ApplicationServiceDB"
  user: "postgres"
  pass: "root"
  port: "5432"
  ssl_model: "disable"


HTTP_SERVER_INFO:
  host: "172.16.0.196"
  port: "8082"

JWT_TEMP_INFO:
  key: "lololololololololololololololololololololololololololololol"


RABBIT_INFO:
  address_path: "amqp://app:test@172.16.0.94:5672/"
  queue_name: "olymp_application"

ADDITIONAL_ADDRESSES:
  react: "http://172.16.1.196:5173"
  jure-assignments: "http://localhost:8090"
  olymp-result: "http://172.16.0.94:8080"