env: "local"

DB_INFO:
  host: "localhost"
  user: "postgres"
  pass: "timur"
  name: "ApplicationServiceDB"
  port: "5432"
  ssl_model: "disable"


HTTP_SERVER_INFO:
  host: "localhost"
  port: "8080"

JWT_TEMP_INFO:
  key: "lololololololololololololololololololololololololololololol"


ADDITIONAL_ADDRESSES:
  react: "http://localhost:5173"