env: "dev"

DB_INFO:
  host: "localhost"
  name: "EventServiceDB"
  user: "postgres"
  pass: "root"
  ssl_model: "disable"


HTTP_SERVER_INFO:
  host: "172.16.1.39"
  port: "8080"

JWT_INFO:
  key: "lololololololololololololololololololololololololololololol"

RABBIT_INFO:
  address_path: "amqp://event:test@172.16.0.94:5672/"
  queue_name: "olymp_event"

# KIZNAIVER_INFO:
#   services: [
#     "olymp_app": "applications",
#     "olymp_jury": "jury_assigments"
#   ]

ADDITIONAL_ADDRESSES:
  react: "http://172.16.1.39:5173"
  jure-assignments: "http://localhost:8090"
  olymp-result: "http://172.16.0.94:8080"