env: "local"

DB_INFO:
  host: "localhost"
  name: "EventServiceDB"
  user: "postgres"
  pass: "root"
  ssl_model: "disable"


HTTP_SERVER_INFO:
  host: "localhost"
  port: "8080"
  
ADDITIONAL_ADDRESSES:
  react: "http://localhost:5173"