env: "dev"

HTTP_SERVERS_INFO:
  routes:
    # ==================== AUTH SERVICE (8181) ====================
    - prefix: "/auth"
      aggregate: false
      target: "http://172.16.1.39:8181/api/users/login"
      skip_auth: true

    - prefix: "/logout"
      aggregate: false
      target: "http://172.16.1.39:8181/api/users/logout"
      skip_auth: false

    - prefix: "/refresh"
      aggregate: false
      target: "http://172.16.1.39:8181/api/users/refresh"
      skip_auth: true

    - prefix: "/register"
      aggregate: false
      target: "http://172.16.1.39:8181/api/users/register"
      skip_auth: true

    - prefix: "/revoke-all"
      aggregate: false
      target: "http://172.16.1.39:8181/api/users/revoke-all"
      skip_auth: false

    - prefix: "/users/"
      aggregate: false
      target: "http://172.16.1.39:8181/api/users"
      skip_auth: false

    - prefix: "/users/count"
      aggregate: false
      target: "http://172.16.1.39:8181/api/users/count"
      skip_auth: false

    # ==================== PARTICIPANTS & SCHOOLS SERVICE (8181) ====================
    - prefix: "/participants/"
      aggregate: false
      target: "http://172.16.1.39:8181/api/participants"
      skip_auth: false

    - prefix: "/participants/byuser/"
      aggregate: false
      target: "http://172.16.1.39:8181/api/participants/byuser"
      skip_auth: false

    - prefix: "/participants/count"
      aggregate: false
      target: "http://172.16.1.39:8181/api/participants/count"
      skip_auth: false

    - prefix: "/schools/"
      aggregate: false
      target: "http://172.16.1.39:8181/api/schools"
      skip_auth: false

    - prefix: "/schools/count"
      aggregate: false
      target: "http://172.16.1.39:8181/api/schools/count"
      skip_auth: false

    # ==================== EVENTS SERVICE (8080) ====================
    - prefix: "/events/"
      aggregate: false
      target: "http://172.16.1.39:8080/api/events"
      skip_auth: false

    - prefix: "/events/child/"
      aggregate: false
      target: "http://172.16.1.39:8080/api/events/child"
      skip_auth: true

    - prefix: "/events/class/"
      aggregate: false
      target: "http://172.16.1.39:8080/api/events/class"
      skip_auth: false

    - prefix: "/events/subjects/"
      aggregate: false
      target: "http://172.16.1.39:8080/api/events/subjects"
      skip_auth: false

    - prefix: "/regional-stages"
      aggregate: false
      target: "http://172.16.1.39:8080/api/events/regional-stage"
      skip_auth: true

    # ==================== APPLICATIONS SERVICE (8082) ====================
    - prefix: "/applications/"
      aggregate: false
      target: "http://172.16.0.196:8082/applications"
      skip_auth: false

    - prefix: "/applications/count"
      aggregate: false
      target: "http://172.16.0.196:8082/applicationsCount"
      skip_auth: false

    - prefix: "/applications/event/"
      aggregate: false
      target: "http://172.16.0.196:8082/applications/event"
      skip_auth: false

    # ==================== JURY SERVICE (8090) ====================
    - prefix: "/jury-assignments/event/"
      aggregate: false
      target: "http://172.16.1.39:8090/api/jury-assignments/event"
      skip_auth: false

    # ==================== AGGREGATE ROUTES ====================
    - prefix: "/AplicationEvent"
      aggregate: true
      services:
        - "http://172.16.0.196:8082/applications"
        - "http://172.16.1.39:8080/api/events"
      skip_auth: true
      roles: []

    - prefix: "/ApplicationEventtest/"
      aggregate: true
      targets:
        - url: "http://172.16.0.196:8082/applications/user/"
          fields: ["id", "status"]
        - url: "http://172.16.0.196:8082/api/events/list/"
          fields: ["id", "name", "start_date", "end_date", "previous_event_id", "subject", "class_number", "additional_info"]
      skip_auth: false
      roles: []  
    - prefix: "/ApplicationEvent/"
      aggregate: true
      targets:
        - url: "http://172.16.0.196:8082/applications/user/"
          fields: [""]
        - url: "http://172.16.1.39:8080/api/events/list"
          fields: [""]
      skip_auth: false
      roles: []  


CORS_INFO:
  allow_origins: [
    http://172.16.0.196:5173,
    http://172.16.0.94:59871,
    http://172.19.0.1:5173
  ]

HTTP_SERVER_MAIN_INFO:
  address: "172.16.0.196"
  port: "6611"

JWT_TEMP_INFO:
  key: "lololololololololololololololololololololololololololololol"

REDIS_INFO:
  address_path: "redis:6379"

RABBIT_INFO:
  address_path: "amqp://app:test@172.16.0.94:5672/"
  queue_name: "olymp_application"
