env: "dev"

HTTP_SERVER_INFO:
  routes:
    - prefix: "/auth"
      target: "http://172.16.0.196:8082/applications"
      skip_auth: true
    - prefix: "/profile"
      aggregate: true
      services:
        - "http://172.16.0.196:8082/applications"
        - "http://172.16.1.39:8080/api/events"
      skip_auth: true
      roles: []

JWT_TEMP_INFO:
  key: "..."

REDIS_INFO:
  address_path: "redis:6379"

RABBIT_INFO:
  address_path: "amqp://app:test@172.16.0.94:5672/"
  queue_name: "olymp_application"
