env: "dev"

DB_INFO:
  host: "localhost"
  name: "SSOServiceDB"
  user: "postgres"
  pass: "root"
  ssl_model: "disable"


HTTP_SERVER_INFO:
  host: "172.16.1.39"
  port: "8181"

JWT_INFO:
  key: "lololololololololololololololololololololololololololololol"
  duration: 30

REDIS_INFO:
  address_path: "172.16.0.94:6379"

ADDITIONAL_ADDRESSES:
  react: "http://172.16.1.39:5173"
  jure-assignments: "http://localhost:8090"
  olymp-result: "http://172.16.0.94:8080"
  event: "http://172.16.1.39:8080"